djangoforum/core/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('signup/', views.signup, name='signup'),
    path('login/', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

djangoforum/djangoforum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('story.urls')),
]

djangoforum/story/urls.py
from django.urls import path

from . import views

app_name = 'story'

urlpatterns = [
    path('creat/', views.creat, name='creat'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/vote/', views.vote, name='vote'),
]

djangoforum/core/models.py
from django.db import models

# Create your models here.

djangoforum/story/models.py
from django.contrib.auth.models import User
from django.db import models


class Story(models.Model):
    title = models.CharField(max_length = 255)
    url = models.URLField(blank = True, null = True)
    text = models.TextField(blank = True, null = True)

    created_at = models.DateTimeField(auto_now_add = True)
    created_by = models.ForeignKey(User, related_name = 'stories', on_delete = models.CASCADE)
    
class Comment(models.Model):
    story = models.ForeignKey(Story, related_name='comments', on_delete=models.CASCADE)
    text = models.TextField()

    created_at = models.DateTimeField(auto_now_add = True)
    created_by = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    
class Vote(models.Model):
    story = models.ForeignKey(Story, related_name='votes', on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add = True)
    created_by = models.ForeignKey(User, related_name='story_votes', on_delete=models.CASCADE)
    

djangoforum/story/forms.py
from django.forms import ModelForm

from .models import Story, Comment

class StoryForm(ModelForm):
    class Meta:
        model = Story
        fields = ('title', 'url', 'text',)

class CommentForm(ModelForm):
    class Meta:
        model = Comment

        fields = ('text',)

djangoforum/core/views.py
import datetime

from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

from story.models import Story

def index(request):
    today = datetime.date.today()

    stories = Story.objects.all()[0:50]

    return render(request, 'core/index.html', {
        'stories': stories
    })

def new(request):
    today = datetime.date.today()

    stories = Story.objects.filter(created_at__gte=today).order_by('-created_at')

    return render(request, 'core/new.html', {
        'stories': stories
    })

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:    
        form = UserCreationForm()

    return render(request, 'core/signup.html',
        {'form' : form}              
    )


djangoforum/story/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import StoryForm, CommentForm
from .models import Story, Comment, Vote

def detail(request, pk):
    story = Story.objects.get(pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.story = story
            comment.created_by = request.user
            comment.save()

            return redirect('story:detail', pk=pk)
        
    else:
        form = CommentForm()

    return render(request, 'story/detail.html', {
        'story': story,
        'form' : form,
    })

@login_required
def vote(request, pk):
    story = Story.objects.get(pk=pk)

    already_voted = story.votes.filter(created_by=request.user)

    if not already_voted:
        Vote.objects.create(story=story, created_by=request.user)

    redirect_page = request.GET.get('redirect_page', '/')

    if redirect_page == "detail":
        return redirect('story:detail', pk=pk)

    else:
        return redirect(redirect_page)

@login_required
def creat(request):
    if request.method == 'POST':
        form = StoryForm(request.POST)
    
        if form.is_valid():
            story = form.save(commit=False)
            story.created_by = request.user
            story.save()

            return redirect('/')
    else:

        form = StoryForm()

    return render(request, 'story/creat.html',
        {'form': form}
    )


djangoforum/core/templates/core/base.html
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <title>{% block title %}{% endblock %} | My journey of Neetcode 150 </title>
    </head>
    <body>
        <div class="max-w-7xl mx-auto p-1">
            <nav class="py-6 flex items-center justify-between bg-teal-500">
                <div>
                    <a href="{% url 'core:index' %}" class="mr-2 font-bold"> My journey of Neetcode 150  </a>
                    <a href="{% url 'core:new' %}"> New |</a>
                    <!-- <a href="#"> Two pointers |</a>
                    <a href="#"> Heap |</a> -->
                    <a href="{% url 'story:creat' %}"> Submit </a>
                </div>

                <div class="flex">
                    {% if request.user.is_authenticated %}
                        <a href="#">{{request.user.username}}</a>
                        <p class="px-2"> | </p>
<!--                         <a href="{% url 'core:logout' %}">Logout</a> -->
                        <form action="{% url 'core:logout' %}" method="post">
                            {% csrf_token %} 

                            <button type="submit">Logout</button> 
                        </form>
                    {% else %}
                        <a href="{% url 'core:login' %}"> Login </a>
                        <p class="px-2"> | </p>
                        <a href="{% url 'core:signup' %}"> Signup </a>
                    {% endif %} 
                </div>
            </nav>
            <main>
                {% block content %}

                {% endblock %}
            </main>
            <footer>
                <div>
                    <p class="" style="text-align: center; font-style:italic; font-weight: lighter; font-size: smaller;">
                        "What do you desire? Money and wealth? Glory? Honor and pride? Authority and power? Revenge? Or something that transcends all of them? Whatever you desire - is in here."
                    </p>
                </div>
            </footer>
            </div>
    </body>
</html>

djangoforum/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %} Welcome {% endblock %}

{% block content%}
{% for stories in stories %}
    <div class="py-6 bg-teal-500 flex">
        <div class="flex">
            <p>{{ forloop.counter }}.</p>

            <a a href="{% url 'story:vote' stories.id %}?redirect_page=core:index">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 18.75 7.5-7.5 7.5 7.5" />
                    <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 7.5-7.5 7.5 7.5" />
                </svg>          
            </p>
        </div>
        <div>
            <p>
                <a href="{% url 'story:detail' stories.id %}">{{stories.title}} </a>

                {% if stories.url %}
                    <a class="text-gray-500" href="{{stories.url}}">{{stories.url}}</a>
                {% endif %} 
            </p>
        
            <div class="flex text-gray-500">
                <p>
                    {{ stories.votes.count}} points by {{stories.created_by.username}} {{stories.created_at|timesince }} ago
                </p>
                <p class="px-3"> | 

                </p>
                <p>
                    {{ stories.comments.count }} comments
                </p>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}

djangoforum/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %} Login {% endblock %}

{% block content%}
    <div class="p-2 bg-gray-200 font-bold">
        <h1>
           Login
        </h1>
        <form method="post" action=".">
         {% csrf_token %}
         
         {{form.as_p}}

         <button class="mt-5 p-1 rounded-sm border-gray-500">Submit</button>
        </form>
    </div>

{% endblock %}

djangoforum/core/templates/core/new.html
{% extends 'core/base.html' %}

{% block title %} New {% endblock %}

{% block content%}
{% for stories in stories %}
    <div class="py-6 bg-teal-500 flex">
        <div class="flex">
            <p>{{ forloop.counter }}.</p>

            <a a href="{% url 'story:vote' stories.id %}?redirect_page=core:new">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 18.75 7.5-7.5 7.5 7.5" />
                    <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 7.5-7.5 7.5 7.5" />
                </svg>          
            </a>
        </div>
        <div>
            <p>
                <a href="{% url 'story:detail' stories.id %}">{{stories.title}} </a>

                {% if stories.url %}
                    <a class="text-gray-500" href="{{stories.url}}">{{stories.url}}</a>
                {% endif %} 
            </p>
        
            <div class="flex text-gray-500">
                <p>
                   {{ stories.votes.count}} points by {{stories.created_by.username}} {{stories.created_at|timesince }} ago
                </p>
                <p class="px-3"> | 

                </p>
                <p>
                    {{ stories.comments.count }} comments
                </p>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}

djangoforum/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %} Sign up {% endblock %}

{% block content%}
    <div class="p-2 bg-gray-200 font-bold">
        <h1>
           Sign up 
        </h1>
        <form method="post" action=".">
         {% csrf_token %}
         
         {{form.as_p}}

         <button class="mt-5 p-1 rounded-sm border-gray-500">Submit</button>
        </form>
    </div>

{% endblock %}

djangoforum/story/templates/story/creat.html
{% extends 'core/base.html' %}

{% block title %} Create Content {% endblock %}

{% block content%}
    <style>
        .button{
            text-shadow: 2px 2px 5px black;
        }
    </style>

    <div class="p-2 bg-gray-200 font-bold">
        <h1>
           Create Content
        </h1>
        <form method="post" action=".">
         {% csrf_token %}
         
         <!-- {{form.as_p}} -->

        <div style="margin-bottom: 10px;">
            Title : {{ form.title }}
        </div>
        <div style="margin-bottom: 10px;">
            Url : {{ form.url }}
        </div>
        <div style="margin-bottom: 10px;">
            Text : {{ form.text }}
        </div>

         <button class="mt-5 p-1 rounded-sm button" style="background-color: rgb(5, 169, 112); color: white;">Submit</button>
        </form>
    </div>

{% endblock %}

djangoforum/story/templates/story/detail.html
{% extends 'core/base.html' %}

{% block title %} {{story.title}} {% endblock %}

{% block content%}
<style>
    .button{
        text-shadow: 2px 2px 5px black;
    }
</style>

<div class="py-6 bg-teal-500 flex">
    <div>
        <a href="{% url 'story:vote' story.id %}?redirect_page=detail">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 18.75 7.5-7.5 7.5 7.5" />
                <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 7.5-7.5 7.5 7.5" />
            </svg>          
        </a>
    </div>
    <div>
        <p>
            <a href="{% url 'story:detail' story.id %}">{{story.title}} </a>

            {% if story.url %}
                <a class="text-gray-500" href="{{story.url}}">{{story.url}}</a>
            {% endif %}
            
            {% if story.text %}
                <pre>
                    <p> {{ story.text|linebreaksbr }} </p>
                </pre>
            {% endif %}
        </p>
    
        <div class="flex text-gray-500">
            <p>
                {{ story.votes.count}} points by {{story.created_by.username}} {{story.created_at|timesince }} ago
            </p>
            <p class="px-3"> | 

            </p>
            <p>
                {{ story.comments.count }} comments
            </p>
        </div>
    </div>
</div>

<div class="bg-gray-200 font-bold">
    {% if request.user.is_authenticated %}
        <form method="post" action=".">
            {% csrf_token %}

            {{ form.as_p }}
                
<!--             <div style="margin-left: 10px;">
                Text : {{ form.text}}
            </div> -->
            
    
            <button class="mt-5 p-1 rounded-sm button" style="margin-bottom: 10px; margin-left: 10px; background-color: rgb(5, 169, 112); color: white;">Submit</button>
        </form>
    {% else %}
        <p>You need to log in to submit a comment!</p>
    {% endif %}
</div>

<div class="bg-gray-200 font-bold" style="margin-top: 10px;">
    {% for comment in story.comments.all %}
        <div class="p-2">
            <p class="text-gray-500">
                {{ comment.created_by.username}}
                |
                {{ comment.created_at|timesince}} ago
            </p>

            <pre>
                <p class="mt-2">
                    {{ comment.text|linebreaksbr }}
                </p>
            </pre>
            
        </div>
    {% endfor %}
</div>
{% endblock %}